### ISSUE TITLE
how to try this application

### ISSUE THREAD

**Issue by legacychimera247** [matzipan/envoyer#244]
hello, actually very nice to have a gtk4 mail client

any more easy way to try out this application? :) like a copr or a flatpak?

**Comment by matzipan** [comment]
Hey - sorry for the late response. The best bet for you to try it is to do a local build following [the steps in the readme](https://github.com/matzipan/envoyer/blob/main/README.md#building). It should not be too difficult if you have flatpak and git around. 

I won't be publishing any flatpaks as of yet as the experience is not very friendly from a user perspective. Maybe by end of v0.3
