### ISSUE TITLE
Move to MailCore

### ISSUE THREAD

**Issue by matzipan** [matzipan/envoyer#57]

**Comment by eyelash** [comment]
Does MailCore have a C API or only a C++ API? If it's the latter then what is the plan? Write a GObject wrapper for MailCore? Try to work with MailCore upstream to add a C wrapper? Write the app in C++ instead of Vala?

**Comment by matzipan** [comment]
Hey eyelash,

Wasn't aware other people are paying attention, otherwise I would've been more descriptive around here.

Yes, MailCore 2 is a C++ only API. 

For a moment, I contemplated whether using glibmm/gtkmm and write the whole client in C++ would be a good solution, but decided it is not the best approach, since this would mean having to write wrappers for any other GObject library (such as Granite, Soup, WebkitGTK). 

Since MailCore 2 seems a pretty slow moving target, and I'm trying to get an MVP out the door as fast as possible, a quick and dirty GObject wrapper seems like a good solution. If the wrapper reaches an advanced and refined state, perhaps it's worth reaching out to upstream and intergrating this, but for now, I don't have the time to do this. 

You can see the current wrapper code in the last commit, in [this](https://github.com/matzipan/envoyer/tree/master/src/MailCoreInterface) directory. Locally, I have managed to get the sidebar to display all the folders and I should be able to get it fully working (the sidebar) and committed later today. 

I was extremely frustrated with the complexity of EDS, and I believe there was a fair amount of technical debt in there too. I was able to read the folders and the context of my inbox with MailCore in less than 10 lines. AFAICT, with MailCore I will have to implement the syncing and offline storage myself, which I'm more than happy to do given the relative ease with which I've interacted with the library so far. MailCore also doesn't provide access to contacts and calendar, but that's a story for another time/app.

**Comment by matzipan** [comment]
If you want to try your luck with the latest commit, you'll have to build and install libetpan from source (the one in the Ubuntu repositories might also work, but I haven't tried), install all the mailcore2 linux dependencies and clone the mailcore2 repository in the same directory you've cloned envoyer. When you build envoyer, it should also build and statically link against mailcore2, if the paths are right.

You will need to `sudo make install` envoyer to get the latest schema in gsettings, and there you'll be able to enter your GMail username and password (I know it's a terrible method, but it'll do for now).

**Comment by eyelash** [comment]
Thanks for the detailed explanation. I didn't know about MailCore until yesterday but I had a look at the code today and it seems pretty nice. I wonder what MailCore actually provides on top of libetpan or if it would make sense to just use libetpan directly (It's a C API). I haven't compiled envoyer yet, I'm just watching this repository because a nice and modern native GTK+ mail client is something I really miss.

**Comment by matzipan** [comment]
There's also https://www.vmime.org/. I chose MailCore because it's used by the AirMail OS X app. 

[This](http://mailcore.tumblr.com/post/52790194722/mailcore-2-the-next-step-of-libetpan) article explains some of the history but I must admit I do not know much about the difference.  If you think you can find some relevant info, I'm listening.

I suspect that etpan handles the lower level interaction, for example formatting the IMAP messages and various stateless protocol methods, while MailCore links them together in a usable model-based manner (ie. I can query all emails from a certain folder without having to keep track the IMAP connection, I just have an IMAPSession which does it for me).

**Comment by eyelash** [comment]
In my head I still think the API that is needed is quite small. Something like

- receive folders
- receive messages for folder
- receive message content
- delete message
- move message to a different folder
- send message

and this looks like it could be implemented in a couple of hundred lines of code no matter the library used but I'm surely missing a lot here because I haven't really spent much time thinking about email clients.

For libetpan there is an [example here](https://github.com/dinhviethoa/libetpan/blob/master/tests/imap-sample.c) which looks a bit more complicated than mailcore2 but maybe it would be worth it considering wrapping the mailcore2 C++ API also takes some effort.

**Comment by matzipan** [comment]
I agree, the actual API functionality that is required is not complicated at all. 

For comparison, this is the yet uncommitted code I use to fetch all the folder names (no types) and put them in a GLib.List:
```
mailcore::ErrorCode error;

    mailcore::Array* folders = session->fetchAllFolders (&error);
    
    GList *list = NULL;

    for(uint i = 0 ; i < folders->count() ; i++) {
        mailcore::IMAPFolder* folder = (mailcore::IMAPFolder*) folders->objectAtIndex(i);
        list = g_list_append (list, g_string_new(folder->path()->UTF8Characters()));
    }
    
    return list;  
```

To fetch all messages in the inbox: 
```

auto uidRange = mailcore::IndexSet::indexSetWithRange(mailcore::RangeMake(1, UINT64_MAX));

mailcore::Array * messages = session->fetchMessagesByUID(new mailcore::String("INBOX"), mailcore::IMAPMessagesRequestKindHeaders, uidRange, NULL, &error);
```

**Comment by eyelash** [comment]
Here is how to print all the folder names using libetpan:

```c
clist *folders;
mailimap_list(imap, "", "*", &folders);
for (clistiter *i = clist_begin(folders); i; i = clist_next(i)) {
	struct mailimap_mailbox_list *mb_list = clist_content(i);
	printf("%s\n", mb_list->mb_name);
}
```

and here is the full example:

```c
#include <libetpan/libetpan.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
	struct mailimap *imap = mailimap_new(0, NULL);
	mailimap_ssl_connect(imap, "imap.gmail.com", 993);
	mailimap_login(imap, argv[1], argv[2]);
	
	clist *folders;
	mailimap_list(imap, "", "*", &folders);
	for (clistiter *i = clist_begin(folders); i; i = clist_next(i)) {
		struct mailimap_mailbox_list *mb_list = clist_content(i);
		printf("%s\n", mb_list->mb_name);
	}
	
	mailimap_logout(imap);
	mailimap_free(imap);
	return 0;
}
```

compile with `gcc -o example -std=c99 example.c -letpan` and run with `./example john@example.com password`

**Comment by matzipan** [comment]
That looks promising, but on closer inspection, MailCore appears to do a lot of things for you, like [syncing](https://github.com/MailCore/mailcore2/blob/65bc5a2c045c38b35709964be614f5ceabc637ed/src/core/imap/MCIMAPSession.cpp#L2397) with the server, [integrate](https://github.com/MailCore/mailcore2/wiki/Changes-From-The-Original-MailCore#providers) [providers](https://github.com/MailCore/mailcore2/blob/c5883419864a2cbc27b9ed8a9dea7651f2c61f17/resources/providers.json) or [search](https://github.com/MailCore/mailcore2/blob/65bc5a2c045c38b35709964be614f5ceabc637ed/src/core/imap/MCIMAPSession.cpp#L3108). Perhaps most importantly, it has an [async](https://github.com/MailCore/mailcore2/tree/c5883419864a2cbc27b9ed8a9dea7651f2c61f17/src/async/smtp) API. 

While the API might not be the best fit, it will get the job done in terms of getting an MVP out. I'd say just use as much of MailCore for now and worry about etpan later if MailCore is not found to be a good fit.

**Comment by matzipan** [comment]
Or perhaps draw from MailCore to write an etpan Glib wrapper.

**Comment by eyelash** [comment]
Yes that was my idea as well. Though seeing that async and provider stuff makes me think this is a bigger task than I thought. Something more than a weekend project. But ultimately I think a MailCore inspired GLib wrapper for libetpan (possibly written in Vala) would be something nice to have and would be a better architecture than trying to use MailCore 2 from a Vala project.

**Comment by matzipan** [comment]
I thought I'd be pushing some code today, but I'll probably do tomorrow. I'm currently stuck with my last few university assignments.

**Comment by matzipan** [comment]
Pushed proper folder fetching. Working on messages now.

**Comment by matzipan** [comment]
Closing this issue as it's followed up by #58
